### PR TITLE
added validation to signup form

### PR DESCRIPTION
**Pull request by sapunethmini**
Here it is with some warning  in the selectbox .temporary i commented that part and ,,,the length of this form varies when add required filed ..will fix it

### CODE REVIEW

**Review by DewBM — CHANGES_REQUESTED** [review]
when signup, password should be validated properly (at least 8 characters, 1 upper case, 1 lower case, 1 digit, 1 symbol)

phoneNumber also should be validated. (only digits with exactly 10 elements)

loginSchema should be renamed as SignUpSchema.

in action.ts, you should create a new function signup() for signup. (not modify the signin function)

**Comment by sapunethmini** [comment]
> when signup, password should be validated properly (at least 8 characters, 1 upper case, 1 lower case, 1 digit, 1 symbol)
> 
> phoneNumber also should be validated. (only digits with exactly 10 elements)
> 
> loginSchema should be renamed as SignUpSchema.
> 
> in action.ts, you should create a new function signup() for signup. (not modify the signin function)

added.

**Review by DewBM — CHANGES_REQUESTED** [review]
make necessary changes

**Comment by sapunethmini** [comment]
> make necessary changes

done!,plz check

**Review by DewBM — APPROVED** [review]
ok. thanks

**Pull request merged**
